### ISSUE TITLE
valueOrThrow

### ISSUE THREAD

**Issue by mgohin** [Nift/Optional#23]
Hi,

maybe I missed the way to do it but I often need to find by criteria something, returning an `Optional` and I need to throw my own exception.

I was using `typescript-optional` and was a Java dev previously, and I'm used to `.orElseThrow`.

Could you add a `.valueOrThrow(() => new MyException(...))` ?

I'd like to use your lib because it manages async ❤️

**Comment by mgohin** [comment]
It's exactly what I wanted ! Didn't read the doc properly !!

Thanks

**Comment by mgohin** [comment]
<img width="991" alt="image" src="https://github.com/Nift/Optional/assets/3430304/6886c100-f07e-4c69-a2f4-5704085ac68c">

Would it be interesting to add a callback function that returns an `Error` ?
So I'd prevent


```typescript
valueOr(alternative: T | (() => T) | Error | (() => Error) | (() => never)): T {
```

**Comment by mgohin** [comment]
(forgot to reopen)

**Comment by mgohin** [comment]
/poke @Nift just in case you did not see the reopening

**Comment by Nift** [comment]
I believe to have fixed it with `valueOrAlternative`. 

This will enable what you want to do, as JavaScript does not have Exceptions but the Error type, meaning that your example above is a custom type rather than an Exception as known from other programming languages. 
I found that `valueOrAlternative` was a better name, as that is more precisely what you do: You wan the value or a different type returned.

**Comment by mgohin** [comment]
The method you implemented is nice for another need I got sometimes, to change the returned type.

But my first request was to throw and exception ('Error' in js yes).

With this method, I think it does not throw the error, I'll just be able to return an `Error` but I'll have to check the returned type and if it's an `Error` then I'll to throw it.

I was hoping you'd do it with the suggested method `valueOrThrow`

**Comment by Nift** [comment]
I do not see how you can not just use `valueOr` which allows for the Error type or use `valueOrFailure` which throws the error with the text you specified?
