### ISSUE TITLE
`tslib` required

### ISSUE THREAD

**Issue by tomsquest** [Nift/Optional#3]
Hi,

I played with your library and I found concise and effective to work with.

I found that `tslib` is a required "indirect" dependency of your lib, as `importHelpers: true` is used in `tsconfig.json`. That means that the code is compiled with `require('tslib')` and the consumer has to provide it (and of course I was not).

**Comment by Nift** [comment]
Hi @tomsquest thanks for using my library! 

I have now updated the code and released a version `1.3.6` that should incorporate your feedback :) Let me know if there is any issues

**Comment by tomsquest** [comment]
Thx !
