### ISSUE TITLE
Rename `valueOrFailure` to `value` or provide an additional method `value` 

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [Nift/Optional#8]
Hi there,

great work with the library. I am coming from a .NET background and there we have [Nullable<>](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types#examination-of-an-instance-of-a-nullable-value-type) that is normally used in a `HasValue` / `Value` pattern. I find it rather odd to use `hasValue` followed by a call to `valueOrFailure` as the call cannot cause a failure when `hasValue` has been called before. The method `valueOrFailure` already provides the default behaviour of .NETs `Value`, that is throwing an error when no value is present. Hence it would be nice to have a `value()` without any parameters.

Enough mumbling, basically the issue is as follows:

`if (x.hasValue) { x.valueOrFailure().foo() }`

vs 

`if (x.hasValue) { x.value().foo() }`

I would always prefer the latter.

So lonG

Daniel

**Comment by Nift** [comment]
Just so I understand it completely, it is more of a "syntactic sugar" thing rather than an actual "feature request"? :) 

I can not remove/rename `valueOrFailure` but could definitely add this for some brevity.
